version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgconf:/etc/postgresql
      - pglogs:/var/log/postgresql
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - postgres

  # need to fix window/linux dependencies 
  # prisma-studio:
  #   image: node:lts-alpine3.17
  #   working_dir: /usr/src/app
  #   volumes:
  #     - .:/usr/src/app
  #   command: npx prisma studio --port 5555 --browser none
  #   ports:
  #     - "${PRISMA_PORT}:5555"
  #   env_file:
  #     - .env
  #   networks:
  #     - postgres
  #   depends_on:
  #     - postgres
    


volumes:
  pgconf:
  pglogs:
  pgdata:
  pgadmin-data:
networks:
  postgres:
